[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
common = { path = "../common" }
config = { path = "../config" }
decode = { path = "../decode" }
execution = { path = "../execution" }
graph = { path = "../graph" }
ingress = { path = "../ingress" }
policy = { path = "../policy" }
reconcile = { path = "../reconcile" }
simulation = { path = "../simulation" }
state = { path = "../state" }
strategy = { path = "../strategy" }
ethers.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
