[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
config = { path = "../config" }
decision = { path = "../decision" }
execution = { path = "../execution" }
ingest = { path = "../ingest" }
types = { path = "../types" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
