[package]
name = "execution"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
config = { path = "../config" }
types = { path = "../types" }
anyhow.workspace = true
async-trait.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
tokio.workspace = true
tracing.workspace = true
