[package]
name = "execution"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
common = { path = "../common" }
ethers.workspace = true
ingress = { path = "../ingress" }
serde_json.workspace = true
strategy = { path = "../strategy" }
async-trait = "0.1"
